---
title: "Data Import"
output: github_document
---

I'm an R Markdown document! 

## Data Import: CSVs
```{r echo=FALSE}
install.packages("tidyverse")
library(tidyverse)
library(haven)
```

Let's import data using 'readr' package
```{r}
litters_df= read_csv("data_import_examples/FAS_litters.csv")
litters_df= janitor:: clean_names(litters_df)
```
```{r, eval=False}
view(litters_df)
```

```{r}
# in the skimr package, use skim function (::)
skimr::skim(litters_df)
```

```{r missing data, skip}
read_csv("data_import_examples/FAS_litters.csv", na=c("", "NA",999,88), skip=2)
```

##other file formats

read excel package
```{r}
library(readxl)
mlb_df=read_excel("data_import_examples/mlb11.xlsx")
# you can choose what sheet you want the data from
```


```{r}
lotr_words_df=
  read_excel("data_import_examples/LotR_Words.xlsx",
             range= "B3:D6")
```

## more formats
Read in a SAS format

```{r}
pulse_df=read_sas("data_import_examples/public_pulse_data.sas7bdat")
```

```{r data export}
write_csv(lotr_words_df,file="data_import_examples/lotr_words_df.csv")
```

##why not base r??
```{r}
dont_do_this_df= read.csv("data_import_examples/FAS_litters.csv")
```

## datawrangling-2 Manipulation
```{r}
library(tidyverse)

options(tibble.print_min = 3)

litters_data = read_csv("./data/FAS_litters.csv",
  col_types = "ccddiiii")
litters_data = janitor::clean_names(litters_data)

pups_data = read_csv("./data/FAS_pups.csv",
  col_types = "ciiiii")
pups_data = janitor::clean_names(pups_data)

```


```{r filter row function}
# is.na() for missing values
filter(pups_data, sex==1)
```


```{r filter row function}
filter(pups_data, pd_walk<11 & sex==2)
```


```{r mutate}
mutate(litters_data,
  wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower(group)
)

```
```{r arrange}
head(arrange(litters_data, group, pups_born_alive), 10)
head(arrange(litters_data, desc(group), pups_born_alive), 10)
```

```{r pipe}
litters_data_raw = read_csv("./data/FAS_litters.csv",
  col_types = "ccddiiii")
litters_data_clean_names = janitor::clean_names(litters_data_raw)
litters_data_selected_cols = select(litters_data_clean_names, -pups_survive)
litters_data_with_vars = 
  mutate(
    litters_data_selected_cols, 
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group))
litters_data_with_vars_without_missing = 
  drop_na(litters_data_with_vars, wt_gain)
litters_data_with_vars_without_missing
```

```{r}
# other way to read things, no intermediate ds, but hard to read
#command shiftM
litters_data = 
  read_csv("./data/FAS_litters.csv", col_types = "ccddiiii") %>%
  janitor::clean_names(dat = .) %>%
  select(.data = ., -pups_survive) %>%
  mutate(.data = .,
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group)) %>% 
  drop_na(data = ., wt_gain)
```



```{r}
# use pipe operator for tibble
litters_data = 
  read_csv("./data/FAS_litters.csv", col_types = "ccddiiii") %>%
  janitor::clean_names() %>%
  select(-pups_survive) %>%
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group)) %>% 
  drop_na(wt_gain)
```

