```{r}
library(tidyverse)
options(tibble.print_min=5)
```

```{r}
pulse_df= haven::read_sas('./data/public_pulse_data.sas7bdat')%>%
  janitor::clean_names()

pulse_tidy_data=
  pivot_longer(
    pulse_df,
    bdi_score_bl: bdi_score_bl:bdi_score_12m,
    names_to = "visit", #name of column variable
    values_to = "bdi",#column name be called of the values
    names_prefix="bdi_score_") # remove redundant prefixes
```

```{r}
pulse_df = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") %>%
  janitor::clean_names() %>%
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit", 
    names_prefix = "bdi_score_",
    values_to = "bdi") %>%
  relocate(visit) %>%
  mutate(
    visit = replace(visit, visit == "bl", "00m"),
    visit = factor(visit)) %>% #originally a character
  arrange(id, visit)
```

```{r}
litters=read_csv("./data/FAS_litters.csv") %>% 
  janitor::clean_names() %>%
  select(litter_number, ends_with("weight")) %>% 
  pivot_longer(
    gd0_weight:gd18_weight,
    names_to = "gd", 
    values_to = "weight") %>% 
  mutate(gd= recode(gd, "gd0_weight"=0, "gd18_weight" =18))

```
```{r}
analysis_result = tibble(
  group = c("treatment", "treatment", "placebo", "placebo"),
  time = c("pre", "post", "pre", "post"),
  mean = c(4, 8, 3.5, 4)
)

analysis_result

analysis_result_wide = pivot_wider(
analysis_result,
names_from = "group",
values_from= "mean"
)
```
```{r}
fellowship_ring = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "B3:D6") %>%
  mutate(movie = "fellowship_ring")

two_towers = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "F3:H6") %>%
  mutate(movie = "two_towers")

return_king = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "J3:L6") %>%
  mutate(movie = "return_of_the_king")

```

```{r}
lotr_tidy = 
  bind_rows(fellowship_ring, two_towers, return_king) %>% 
   janitor::clean_names() %>% 
  pivot_longer(
    female:male,
    names_to= 'gender',
    values_to = 'words'
  ) %>% 
  mutate(race=str_to_lower(race))
```

```{r}
pup_data = 
  read_csv("./data/FAS_pups.csv") %>%
  janitor::clean_names() %>%
  mutate(
    sex = recode(sex, `1` = "male", `2` = "female"), #` tell r you are looking for 1
    sex = factor(sex)) 
```
```{r}
litter_data = 
  read_csv("./data/FAS_litters.csv") %>%
  janitor::clean_names() %>%
  separate(group, into = c("dose", "day_of_tx"), sep = 3) %>%
  relocate(litter_number) %>%
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    dose = str_to_lower(dose))

# join
left_join(pup_data,litter_data)
```

